### PR TITLE
exploration: potential improvement to fitter settings

### PR DESCRIPTION
**Pull request by birdybro**
Current fitter settings were not putting enough effort by Quartus into timing performance or the fit. 8.0x effort multiplier and physical synthesis effort settings increase the effort to fit, initial default seed "1" yielded a successful compile for the first time I've ever seen. QII_AUTO_PACKED_REGISTERS, according to the tooltip says "SPARSE AUTO" to be the best effort at timing performance, and this core needs every bit of timing performance.

I am currently running a 100 seed run in DSE to find out what the best seed is for this build in terms of timing and fmax. When that is completed in a few days I will update this PR with that seed so it can be compiled, along with the test results as documentation in a reply.

I have been testing these improved fitter settings for a few weeks with multiple Design Space Explorer runs on multiple cores and they seem to yield better results.

### CODE REVIEW

**Comment by sorgelig** [comment]
It won't give you "always success" compilation. Believe me, in several years of working on this core i've tried everything. Higher effort may just give you much longer compilation with the same probability of fail. This core has many timings violations and thus will always time after fail to compile or even work after succeeded compilation. I'm not sure if it ever will be possible to fix all timing violation in this core as it pushes Cyclone V beyond its capability.

**Comment by birdybro** [comment]
Thanks for the advice. I'm still running the 100 seed testing in DS as, the goal wasn't fix all of the timing issues but to improve the worst case slack since that should reduce errors, and it was partially to improve the success rate of compilation to aid in reduced development time for developers.

**Comment by sorgelig** [comment]
With every small change fitting re-shuffled completely. In current build you have SEED 100 as a good seed. Change one line of code and you will have to find other seed for new build. There is no universal seed which will always work.

**Comment by birdybro** [comment]
Yup! :) 

I understand that there is no perfect seed, that is not the goal here. 

I assume you use Design Space Explorer for ao486 release builds. Maybe that you were selecting for a certain set of clocks' fMAX, or using the best Geomean fMAX or the best "Quality of Fit" (relationship between Geomean fMAX and best WC slack as far as I can tell), or the one with the best WC setup slack outcome... out of a limited number of seeds (maybe you run 10-20 seeds), when you do a release. My original goal was to explore this possibility of whether it's worth it to run a large sample in DSE and pick the best one by some certain value. Then I discovered all this variation and read the documentation for Quartus some more, and came to the conclusion that optimizing for timing and performance would yield better results, so I started this new build.

For example, there is a wide variation in fMAX across many of the clocks as seen here:

image

These are the successful compilations from a 100 seed DSE run of the previous commit. Some of these fMAX values vary widely, like `emu|pll|pll_inst|altera_pll_i|cyclonev_pll|counter[2].output_counter|divclk` which varies from 60MHz to 167MHz for the same pll.

Not trying to say I'm right or anything, just exploring the possibility with data and testing. My second 100 seed run is halfway complete as of now, so I will come back with data to see if this is worth exploring. 

The goals I have in mind would be to reduce the extreme variability of some of these fMAX values, improving timing of builds, and reduce the number of seeds developers have to attempt before one succeeds, which can reduce development time.

But if my data shows no real value, that's fine too, it was fun to try and learn and explore this anyways. :)

**Comment by birdybro** [comment]
After fitter changes 61/100 succeeded to build. However, the quality of fit for the best case scenario was marginally lower, so it is probably not good to make these changes. I'm still glad I looked into it since I will think differently about these settings from now on. Thanks again!

Here is the exploration summary for reference in case anyone is interested.

image

**Comment by sorgelig** [comment]
I still don't understand how your exploration can help further releases. You explore it only for current code. Any change and the whole exploration need to be started again.
From my experience SEED 1 gives more chance for best result if compilation succeed. Any non-1 value is kind of "punching" of fitter to go non-optimal local route in hope to get more optimal fitting globally. I can be wrong as i don't know the code of Quartus, but i feel it's like i've said.
So if compilation fails then i usually do some meaningless change (like adding trailing space in some OSD config string) and compile again.

**Comment by birdybro** [comment]
I think the title of my pull request was misleading, and probably a bit presumptuous, I apologize for that. 

Before, I thought that I could get the worst-case slack down to a lower value and I thought that the various outclks' f(MAX) could be improved (which I assumed was related to the 100MHz mode not actually being 100MHz). I saw wide variation on counter[2] and counter[5] in the first results. 

In this instance the only advantage that I can see after the results of my test would be improving the success rate of compilation (37% --> 61%) leading to less guess work and compilation time wasted between iterations.

The reason why I ran a 100-seed Design Space Explorer exploration was because I was trying to rule out randomness with a larger sample size. If I got 6/10 successes then it could be a fluke, but 61/100 successes suggests a strong pattern.

Sorry about any confusion.

**Comment by sorgelig** [comment]
I see. i misinterpreted your goal as finding "correct" seed.
Well, i accept this PR in light of better understanding.

**Comment by sorgelig** [comment]
please re-submit PR or change its status, so i will be able to merge it.

**Comment by birdybro** [comment]
Updated! First time I've tried to resolve conflicts in a PR, it looks like it worked!

**Pull request merged**
