### PR TITLE
Request for adding the PC Gameport code.

### PR DESCRIPTION
**Pull request by ElectronAsh**
The main part of the new code is in ao486_MiSTer/rtl/soc/sound/joystick.v

It's quite rudimentary atm, as it's only using the digital joypad values from the HPS.

It could of course be changed to allow "analog" joystick values as well, but I wasn't sure how that is normally handled in hps_io, and I don't think analog sticks are enabled in the ao486 HPS code yet?

Joystick detection seems to work fine now in the few games I've tried, but more testing is required.

50927111_2205146522882015_8020990169903529984_n

### CODE REVIEW

**Comment by ElectronAsh** [comment]
I wasn't sure how the buttons for both joystick usually get mapped to the IO port bits.

There are only 4 bits (upper nibble) for the buttons, and I've currently mapped them like this...

assign JOY_DO = {!JOY2_BUT2, !JOY2_BUT1, !JOY1_BUT2, !JOY1_BUT1, JOY2_Y>0, JOY2_X>0, JOY1_Y>0, JOY1_X>0};

**Comment by sorgelig** [comment]
This is very huge code change. I don't see how all this is related just to joystick port. It should be very simple addon. NextZ80 for joystick? Common!
Please cleanup the code to submit only joystick related code. MPU401 as far as i know is not working yet? Then no need to include it. 
ao486 is already very huge core. I've put a lot of effort to clean the code to minimize it in every possible way.

**Comment by ElectronAsh** [comment]
I thought I was using a fairly recent fork of ao486.

I've only just learning how to use github more.

Don't know where the "NextZ80" thing comes from?

And yes, MPU-401 not quite working yet, but I forgot it was in the fork.

**Comment by ElectronAsh** [comment]
Looks like the NextZ80 stuff was generated by Qsys for some reason.

All I did was add the extra ports for MPU-401 and Gameport joystick, then regenerated the Qsys system.

Don't know where else it would have come from?

**Comment by ElectronAsh** [comment]
OPL3 is using the NextZ80CPU core...

https://cdn.discordapp.com/attachments/493918699863015424/549636149061091328/unknown.png

And this is where Qsys generates the system folder...

https://cdn.discordapp.com/attachments/493918699863015424/549639717109366840/unknown.png

I had to assume that was necessary, but I'm now seeing if it will compile without that folder. If it does, I'll add it to my gitignore, then do a new push.

**Comment by sorgelig** [comment]
my ao486 repository already has correct .gitignore 
Also make sure there won't be signaltap files and other debug files included. Version in qsf should not be changed. 
I suggest to clone my repo again and then add only required changes skipping all intermediate experimental options.

**Comment by ElectronAsh** [comment]
I couldn't avoid it modifying a few other Qsys files, but I've removed that unneeded "system" folder now.

Looks like it generates those at compile time within the "db" folder anyway, so no need to generate. I had no clue about that.

I couldn't easily edit the "sound" module for Qsys either, as it regenerated it, and messed up the signal definitions (readdata_valid, burstbegin etc.).

It's just compiled, though, and still seems to work OK, so hopefully I haven't missed anything out.

**Comment by sorgelig** [comment]
This won't work. It anyway will add all your files first and then delete some of them later. 
Make a new fork of my repo and carefully copy required files and changes related to joystick and then make new PR.
I close this PR as it's already spoiled.

**Pull request closed without merging**
