### PR TITLE
e820 map: Do not reserve VGA frame buffer

### PR DESCRIPTION
**Pull request by alexoughton**
This is a solution for running Windows NT 4 on ao486, with full instructions here: https://misterfpga.org/viewtopic.php?p=44432#p44432

After solving "inaccessible boot device" messages in NT setup (with third-party drivers), I found that there were then errors initializing video (even just for text mode setup). I found that the same error occurs when using the ao486 BIOS with Bochs, but that the currently-released Bochs BIOS does not have this problem.

I compared the current state of the Bochs upstream BIOS source code with that of ao486, and found that this change to the e820 map is the critical difference. I performed basic testing and did not find any detrimental effect on DOS, Windows 3.1 or Linux. However I do not have any specific knowledge of e820 to fully understand the change. I have only taken the working values from the upstream source and applied them here.

### CODE REVIEW

**Comment by birdybro** [comment]
Sorgelig modified this intentionally almost 2 years ago. There must have been a specific reason.

https://github.com/MiSTer-devel/ao486_MiSTer/commit/ca219b1004722a318bfcd0002fb9e5c585b4482a

**Comment by sorgelig** [comment]
unfortunately i don't remember why i modified it. Too much time passed already. Does Win95/98 still work after these changes? Amount of RAM is the same?

**Comment by alexoughton** [comment]
I'm getting closer to understanding why this change has an effect. It appears to be the very first line which is important. In the current version it's reserving 0x0009f000 until 0x000d0000, whereas the Bochs version stops at 0x000a0000. Well, 0x000a0000 just so happens to be where the VGA frame buffer is. It looks like what's happening is NT is respecting that this memory is reserved and therefore can't talk to video at all.

I haven't noticed any differences to the amount of reported memory. I'm going to do a couple more things and get back to you:

1. Test a version which changes just this single number and leaves everything else as-per master.
2. Confirm that Windows 95/98 are still OK with this change.

**Comment by sorgelig** [comment]
Probably it's related to linear frame buffer in some VGA mode. But not sure already. This is completely cleared from my memory :)

**Comment by sorgelig** [comment]
what max resolution/color you get on WinNT with these fixes?

**Comment by sorgelig** [comment]
You SHOULD use bank switching mode for correct work. Linear mode is very specific to implementation.

**Comment by alexoughton** [comment]
I'm testing a version which changes only the first line and leaves everything else unmodified. So far looking good. Will update the PR if no issues.

Windows 3.1: Working
Windows 95: Working
Windows 98: Testing in progress...
Windows NT 4: Working, but need to fully test fresh install end-to-end.
Linux: Working

**Comment by alexoughton** [comment]
Windows 98: Working
Windows NT 4: Working

This PR has been updated to only change this single value, and the title has been updated accordingly.

**Comment by sorgelig** [comment]
after merging i finally realized reserve was for shared folder driver!

**Comment by alexoughton** [comment]
OK, I'll experiment with that and get back to you.

**Comment by sorgelig** [comment]
It's coincidence. misterfs writes and reads in that region, so if it's not reserved then some app (or even OS) may place its data/code and it will be corrupted sooner or later.
If that region isn't good then it can be moved to other address, but need to find such place in first 1MB space and reserve it. So if reserving CE000:CFFFF as a separate region won't work, then you can experiment to reserve same size region in other places. MiSTerFS won't automatically work in new region, but i will adjust it. But of course it's better not to move it as current place more or less OK with other OSes.

**Comment by alexoughton** [comment]
Updated version raised as #97

**Pull request merged**
