### PR TITLE
e820 map: Do not reserve VGA framebugger

### PR DESCRIPTION
**Pull request by alexoughton**
Updated version of https://github.com/MiSTer-devel/ao486_MiSTer/pull/95 which includes an explicit reservation for MisterFS.

Confirmed via Linux dmesg output that the e820 map is reflecting as intended.

Before:
linux e820 with original rom

After:
linux e820 with finer reservation

### CODE REVIEW

**Comment by alexoughton** [comment]
Yes, WintNT works just as before.

**Comment by sorgelig** [comment]
I plan to try to install WinNT again. Saw your guide - pretty lengthy but i will try :)

**Comment by alexoughton** [comment]
It's only lengthy because I'm very verbose. The most important thing is to use the third-party disk driver and don't try to use anything other than standard VGA yet. Things will be unstable until installing at least NT service pack 3, so my guide also includes steps to slipstream SP6 in there. It can be difficult to do a post-install upgrade due to that instability.

**Comment by sorgelig** [comment]
Try to install OS/2 :)
I remember it also had some incompatibilities. May be they are solved already.

**Comment by alexoughton** [comment]
A few of us have been trying to get OS/2 going in the Linux thread. We were hoping my previous IDE change would help but it did not. It doesn't look like this e820 change has helped OS/2 either.

**Comment by alexoughton** [comment]
Oh, if you do install NT: Any insight you may have into why the floppy drive isn't working would be appreciated. Strangely it does work during Windows 2000 setup (although 2000 crashes shortly after first full graphical boot - likely due to lack of FPU).

**Comment by sorgelig** [comment]
floppy is also not working natively on Win9x. I have no idea why. On Win9x it works ok through BIOS routines. May be it's possible to do the same in WinNT, then it will work.

**Pull request merged**
